# Generated by Django 4.2 on 2023-06-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adimage',
            old_name='drug',
            new_name='ad',
        ),
    ]
