# Generated by Django 4.2 on 2023-06-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('district', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('home_number', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
