# Generated by Django 4.2 on 2023-07-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_drug_adimage_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_instruction',
            field=models.CharField(default='', max_length=200),
        ),
    ]
