# Generated by Django 4.2 on 2023-07-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_delivery_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_instruction',
            field=models.TextField(default='', max_length=200),
        ),
    ]
