# Generated by Django 4.2 on 2023-06-02 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('Type_name_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_name', to='api.typename')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_category', to='api.category')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_Company', to='api.company')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_country', to='api.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrugImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='frontend/static/images/drugs/drug/%Y/%m/%d/')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.drug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
